markdown: kramdown
permalink: /:year/:month/:day/:title/

name: "Yongle Zhang"

author: "Yongle Zhang"
atom-baseurl: "http://yonglezh.github.io"
disqus: "zagol"

safe: true
paginate: 16
auto: true

highlighter: rouge
