markdown: rdiscount
permalink: /:year/:month/:day/:title/

name: "Yongle Zhang"

author: "Yongle Zhang"
atom-baseurl: "http://zagol.github.io"
disqus: "zagol"


pygments: true
safe: true
paginate: 16
auto: true

